version: "3.3"
services:
  web:
    container_name: framework-dev
    build: .
    volumes:
      - "~/Projects/research/container/static:/app/server/public"
    ports:
      - "5050:5000"
    restart: always
    env_file: ./.env.dev
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - "~/Projects/research/container/dbData:/data/db"
    ports:
      - "27017:27017"


